#ifndef CGLPSDL1_H
#define CGLPSDL1_h

#ifdef FUNKEY

#define BUTTON_UP SDLK_u
#define BUTTON_DOWN SDLK_d
#define BUTTON_LEFT SDLK_l
#define BUTTON_RIGHT SDLK_r
#define BUTTON_A SDLK_a
#define BUTTON_B SDLK_b
#define BUTTON_MENU SDLK_q
#define BUTTON_VOLDOWN SDLK_m
#define BUTTON_VOLUP SDLK_n
#define BUTTON_SOUNDSWITCH SDLK_y
#define BUTTON_GLOWSWITCH SDLK_x
#define BUTTON_DARKSWITCH SDLK_s

#else

#define BUTTON_UP SDLK_UP
#define BUTTON_DOWN SDLK_DOWN
#define BUTTON_LEFT SDLK_LEFT
#define BUTTON_RIGHT SDLK_RIGHT
#define BUTTON_A SDLK_x
#define BUTTON_B SDLK_c
#define BUTTON_MENU SDLK_ESCAPE
#define BUTTON_VOLDOWN SDLK_PAGEDOWN
#define BUTTON_VOLUP SDLK_PAGEUP
#define BUTTON_SOUNDSWITCH SDLK_s
#define BUTTON_GLOWSWITCH SDLK_g
#define BUTTON_DARKSWITCH SDLK_d

#endif

#define BUTTON_UP_INDEX 0
#define BUTTON_DOWN_INDEX 1
#define BUTTON_LEFT_INDEX 2
#define BUTTON_RIGHT_INDEX 3
#define BUTTON_A_INDEX 4
#define BUTTON_B_INDEX 5
#define BUTTON_MENU_INDEX 6
#define BUTTON_VOLDOWN_INDEX 7
#define BUTTON_VOLUP_INDEX 8
#define BUTTON_SOUNDSWITCH_INDEX 9
#define BUTTON_GLOWSWITCH_INDEX 10
#define BUTTON_DARKSWITCH_INDEX 11

#define BUTTON_COUNT 12

#define DEFAULT_WINDOW_WIDTH 360
#define DEFAULT_WINDOW_HEIGHT 360

#endif