#ifndef CGLPSDL1_H
#define CGLPSDL1_h

#define BUTTON_UP SDLK_UP
#define BUTTON_DOWN SDLK_DOWN
#define BUTTON_LEFT SDLK_LEFT
#define BUTTON_RIGHT SDLK_RIGHT
#define BUTTON_A SDLK_x
#define BUTTON_B SDLK_c
#define BUTTON_MENU SDLK_ESCAPE
#define BUTTON_VOLDOWN SDLK_PAGEDOWN
#define BUTTON_VOLUP SDLK_PAGEUP

#define BUTTON_UP_INDEX 0
#define BUTTON_DOWN_INDEX 1
#define BUTTON_LEFT_INDEX 2
#define BUTTON_RIGHT_INDEX 3
#define BUTTON_A_INDEX 4
#define BUTTON_B_INDEX 5
#define BUTTON_MENU_INDEX 6
#define BUTTON_VOLDOWN_INDEX 7
#define BUTTON_VOLUP_INDEX 8

#define BUTTON_COUNT 9

#define DEFAULT_WINDOW_WIDTH 360
#define DEFAULT_WINDOW_HEIGHT 360

#endif