#ifndef CGLPSDL1_H
#define CGLPSDL1_h

#define BUTTON_UP SDLK_UP
#define BUTTON_DOWN SDLK_DOWN
#define BUTTON_LEFT SDLK_LEFT
#define BUTTON_RIGHT SDLK_RIGHT
#define BUTTON_A SDLK_x
#define BUTTON_B SDLK_c
#define BUTTON_MENU SDLK_ESCAPE
#define BUTTON_VOLDOWN SDLK_PAGEDOWN
#define BUTTON_VOLUP SDLK_PAGEUP
#define BUTTON_SOUNDSWITCH SDLK_s

#define DEFAULT_WINDOW_WIDTH 360
#define DEFAULT_WINDOW_HEIGHT 360

#endif