#ifndef CGLPSDL1_H
#define CGLPSDL1_h

#define BUTTON_UP SDLK_UP
#define BUTTON_DOWN SDLK_DOWN
#define BUTTON_LEFT SDLK_LEFT
#define BUTTON_RIGHT SDLK_RIGHT
#define BUTTON_A SDLK_x
#define BUTTON_B SDLK_c
#define BUTTON_MENU SDLK_ESCAPE
#define DEFAULT_WINDOW_WIDTH 640
#define DEFAULT_WINDOW_HEIGHT 360

#endif