#ifndef CGLPSDL1_H
#define CGLPSDL1_h

#define BUTTON_UP SDLK_UP
#define BUTTON_DOWN SDLK_DOWN
#define BUTTON_LEFT SDLK_LEFT
#define BUTTON_RIGHT SDLK_RIGHT
#define BUTTON_A SDLK_X
#define BUTTON_B SDLK_C
#define BUTTON_MENU SDLK_ESCAPE
#define BUTTON_VOLDOWN SDLK_PAGEDOWN
#define BUTTON_VOLUP SDLK_PAGEUP
#define BUTTON_SOUNDSWITCH SDLK_S
#define BUTTON_GLOWSWITCH SDLK_G
#define BUTTON_DARKSWITCH SDLK_D

#define BUTTON_UP_INDEX 0
#define BUTTON_DOWN_INDEX 1
#define BUTTON_LEFT_INDEX 2
#define BUTTON_RIGHT_INDEX 3
#define BUTTON_A_INDEX 4
#define BUTTON_B_INDEX 5
#define BUTTON_MENU_INDEX 6
#define BUTTON_VOLDOWN_INDEX 7
#define BUTTON_VOLUP_INDEX 8
#define BUTTON_SOUNDSWITCH_INDEX 9
#define BUTTON_GLOWSWITCH_INDEX 10
#define BUTTON_DARKSWITCH_INDEX 11

#define BUTTON_COUNT 12

#define DEFAULT_WINDOW_WIDTH 360
#define DEFAULT_WINDOW_HEIGHT 360

#endif