# Controls when the workflow will run
on:
  # Allows you to run this workflow manually target the Actions tab
  workflow_dispatch:

name: Build Windows
jobs:
  build:
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64, name: Cglpsdl2 }
          - { sys: mingw32, env: i686,   name: Cglpsdl2 }
    runs-on: windows-latest    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Msys
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          install: >-
            base-devel
            mingw-w64-${{matrix.env}}-gcc
            mingw-w64-${{matrix.env}}-SDL2             
            mingw-w64-${{matrix.env}}-make

      - name: Build Game
        shell: msys2 {0}
        run: |
          make -f ./src/cglpSDL2/Makefile "EXE=\"${{matrix.name}}.exe\"" "PREFIX=/${{matrix.sys}}"

      - name: Copy Game And Assets
        shell: msys2 {0}
        run: |
          mkdir ./Release
          mkdir "./Release/${{matrix.name}}"
          cp "${{matrix.name}}.exe" "./Release/${{matrix.name}}/"
          cp ./README.md "./Release/${{matrix.name}}/"
          cp ./LICENSE.txt "./Release/${{matrix.name}}/"

      - name: Copy dll libraries
        shell: msys2 {0}
        run: |
          cp /${{matrix.sys}}/bin/libstdc*.dll "./Release/${{matrix.name}}/"
          cp /${{matrix.sys}}/bin/SDL2.dll "./Release/${{matrix.name}}/"
          
      - name: Store build
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.name}} ${{ matrix.env }}
          path: ./Release/
